# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a1ffc0748d1f184eca5646622a65f51110b45b2f2007710c87f7bba06b2219ea6c4c56a847ae552b787217b1d2f9376f0863fee573578cdecbf11a872d75037

test:
  secret_key_base: 31e3afbe799ce0f4d3a09314e9201b8ac6ce1133aac4ae37aed1e00fda7d3deb3b09807deaa6f055627cd2a2ad6471564affdfd5ae5415d4144d65ccb9e2b67f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
